
import type { LucideIcon } from 'lucide-react';

export interface SavedQuestion {
  id: string;
  text: string;
  answer: string; // Added answer field
  questionType: string;
  gradeLevel: string;
  subject: string;
  chapter: string;
  timestamp: number;
}

export interface QuestionContext {
  gradeLevel: string;
  subject: string;
  chapter: string;
  questionType: string;
}

// This type represents a question-answer pair as generated by the AI
export interface GeneratedQuestionAnswerPair {
  question: string;
  answer: string;
}

// Deprecated, use GeneratedQuestionAnswerPair if context is not needed, or combine with QuestionContext if it is.
// For now, QuestionList and page.tsx will handle GeneratedQuestionAnswerPair directly.
export interface GeneratedQuestionItem extends QuestionContext {
  text: string;
  answer: string; // Added answer field
}


export interface SubjectOption {
  value: string;
  label: string;
  icon?: LucideIcon;
}

export interface QuestionTypeOption {
  value: string;
  label: string;
}
